### ISSUE TITLE
Unnecessary Indent 

### ISSUE THREAD

**Issue by monetteContensive** [mattberkowitz/autoclose-html#211]
Not a bug, per se, but the autocomplete tag indents one level, so the tags aren't in the same column: 
i.e. 
<div>
          </div>

Is there a way/setting to get them to line up correctly without having to manually hit the backspace every time?

**Comment by jaaywags** [comment]
I have a solution. Pretty simple. It requires manually changing the package though.

1. Open Atom
2. Go to "Packages" tab
3. Click "Settings View"
4. Click "Manage Packages"
5. Find the "autoclose-html" package
6. Click "Settings"
7. Click "View Code"
8. Open "/autoclose-html/lib/configuration.coffee"
9. Add this at the bottom of the file
```
        alignClosingTag:
            title: "Align the Closing Tag to the Same Column"
            description: "When an element is autoclosed, the closing tag will align to the same column as the opening tag."
            type: 'boolean'
            default: false
```
10. Open "/autoclose-html/lib/autoclose-html-coffee"
11. Add this after line 14
`alignClosingTag: false`
12. Add this after line 48
```
        atom.config.observe 'autoclose-html.alignClosingTag', (value) =>
            @alignClosingTag = value
```
13. Add this after line 121
```
            if @alignClosingTag
                editor.backspace()
```
14. Save and restart Atom
15. Go to "Packages" tab
16. Click "Settings View"
17. Click "Manage Packages"
18. Find the "autoclose-html" package
19. Click "Settings"
20. Click the "Align the Closing Tag to the Same Column" checkbox
21. All done!

I created a [pull-request](https://github.com/mattberkowitz/autoclose-html/pull/212) with this change. 

There is also this open [pull-request](https://github.com/mattberkowitz/autoclose-html/pull/210/commits/55e35044942bc51767caa7263690ecdae6ed2f48) to fix your issue.
